// src/types/api/constants/yeopjeonAction.ts
export const YeopjeonAction = {
  VIEW_DOCUMENT_CHEONMIN_POST: "VIEW_DOCUMENT_CHEONMIN_POST",
  VIEW_DOCUMENT_JUNGIN_POST: "VIEW_DOCUMENT_JUNGIN_POST",
  VIEW_DOCUMENT_YANGBAN_POST: "VIEW_DOCUMENT_YANGBAN_POST",
  VIEW_DOCUMENT_KING_POST: "VIEW_DOCUMENT_KING_POST",
  PURCHASE_DOCUMENT: "PURCHASE_DOCUMENT",
  DOCUMENT_UPLOADER_REWARD: "DOCUMENT_UPLOADER_REWARD",
  RECEIVE_LIKE: "RECEIVE_LIKE",
  RECEIVE_DISLIKE: "RECEIVE_DISLIKE",
  ATTENDANCE_BONUS: "ATTENDANCE_BONUS",
  RECEIVE_REPORT_PENALTY: "RECEIVE_REPORT_PENALTY",
  CREATE_QUESTION_POST: "CREATE_QUESTION_POST",
  DELETE_POST: "DELETE_POST",
  CHAETAEK_CHOSEN: "CHAETAEK_CHOSEN",
  CHAETAEK_ACCEPT: "CHAETAEK_ACCEPT",
  COPYRIGHT_VIOLATION: "COPYRIGHT_VIOLATION",
  REPORT_REWARD: "REPORT_REWARD",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  REWARD_YEOPJEON: "REWARD_YEOPJEON",
  ADMIN_ADJUST: "ADMIN_ADJUST",
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type YeopjeonAction = keyof typeof YeopjeonAction;
